### PR TITLE
(On Distributions) make is possible to use the packaged qoi library.

### PR DESCRIPTION
**Pull request by coldtobi**
by:
- adding third_party to the include paths
- just #include <qoi.h> instead of <third_party/qoi.h>

### CODE REVIEW

**Comment by hzeller** [comment]
Looks good. For using the packaged headers in the distribution, would we need some flag in cmake to use the the local library, or do you rely on system search path finding it before the added `-Ithird_party/` include path ?

While at it, it might be useful to do something similar to `stb_image.h`. Would you like to do that here or in a separate PR ?

**Comment by coldtobi** [comment]
> Looks good. For using the packaged headers in the distribution, would we need some flag in cmake to use the the local library, or do you rely on system search path finding it before the added `-Ithird_party/` include path ?

Good point. (For Debian I simply delete the file before building, but generally you're right that it might pick up the wrong one if it is not done…)

> While at it, it might be useful to do something similar to stb_image.h. Would you like to do that here or in a separate PR ?

Another good point :) I though that it isn't packaged for Debian, but apparently it [is](https://tracker.debian.org/pkg/libstb)… I'll investigate and take a look if it is possible to use it for timg and if so will provide an PR as well…

**Comment by coldtobi** [comment]
@hzeller Added some logic to detect if there is a system qoi.h before adding the include directory.
To make things easier for stb later, I've moved qoi in its own directory.

**Comment by hzeller** [comment]
Nice!

**Pull request merged**
